import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import NavBar from "@/components/nav-bar";
import { Box, Flex } from "@chakra-ui/react";
import MobileNavBar from "@/components/mobile-nav-bar";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "tamplate medical",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} ${poppins.className}`}>
        <Flex justifyContent="center" direction={"column"} bg={"#f7fcfd"}>
          <Providers>
            <NavBar />
            <MobileNavBar />
            <Box marginX={[2, 2, 2, 10, 200, 250]} bg={"#f7fcfd"}>
              {children}
            </Box>
          </Providers>
        </Flex>
      </body>
    </html>
  );
}
